### ISSUE TITLE
Hackage documentation missing

### ISSUE THREAD

**Issue by expipiplus1** [bartavelle/stateWriter#3]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by bartavelle** [comment]
I thought it just meant hackage dropped the baby, as build failures are usually seen in the build logs.

I'll try to fix the docs tonight.

**Comment by bartavelle** [comment]
Done!

**Comment by expipiplus1** [comment]
Thanks!
